export const imposterSetupUrl = 'http://localhost:9999/__add-mock-endpoints__'
export const imposterClearUrl = 'http://localhost:9999/__clear-mock-endpoints__'
export const snapshotClearUrl = 'http://localhost:9999/__clear-snapshots__'
export const createSnapshotUrl = 'http://localhost:9999/__create-debug-snapshot__'
export const debuggerUrl = 'http://localhost:9999/__debugger__'
export const mockedHttpBaseUrl = 'http://localhost:9999'
